/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CitizenRouteImport } from './routes/citizen'
import { Route as CitizenLoginRouteImport } from './routes/citizen-login'
import { Route as OfficerRouteImport } from './routes/officer'
import { Route as OfficerLoginRouteImport } from './routes/officer-login'
import { Route as CitizenIndexRouteImport } from './routes/citizen.index'
import { Route as CitizenAreaBoundaryRouteImport } from './routes/citizen.area-boundary'
import { Route as CitizenDocumentsRouteImport } from './routes/citizen.documents'
import { Route as CitizenLandHealthRouteImport } from './routes/citizen.land-health'
import { Route as CitizenMapRouteImport } from './routes/citizen.map'
import { Route as CitizenMyLandsRouteImport } from './routes/citizen.my-lands'
import { Route as CitizenNotificationsRouteImport } from './routes/citizen.notifications'
import { Route as CitizenProfileRouteImport } from './routes/citizen.profile'
import { Route as CitizenReVerificationRouteImport } from './routes/citizen.re-verification'
import { Route as CitizenReportIssueRouteImport } from './routes/citizen.report-issue'
import { Route as CitizenReportsRouteImport } from './routes/citizen.reports'
import { Route as CitizenRequestsRouteImport } from './routes/citizen.requests'
import { Route as CitizenSearchLandRouteImport } from './routes/citizen.search-land'
import { Route as CitizenSurveyHistoryRouteImport } from './routes/citizen.survey-history'
import { Route as OfficerIndexRouteImport } from './routes/officer.index'
import { Route as OfficerAiDiscrepancyRouteImport } from './routes/officer.ai-discrepancy'
import { Route as OfficerAuditTrailRouteImport } from './routes/officer.audit-trail'
import { Route as OfficerBoundaryEvolutionRouteImport } from './routes/officer.boundary-evolution'
import { Route as OfficerConfidenceRouteImport } from './routes/officer.confidence'
import { Route as OfficerCrossParcelRouteImport } from './routes/officer.cross-parcel'
import { Route as OfficerDroneSurveyRouteImport } from './routes/officer.drone-survey'
import { Route as OfficerEarlyWarningRouteImport } from './routes/officer.early-warning'
import { Route as OfficerEvidenceConflictRouteImport } from './routes/officer.evidence-conflict'
import { Route as OfficerFieldVerificationRouteImport } from './routes/officer.field-verification'
import { Route as OfficerLandRecordsRouteImport } from './routes/officer.land-records'
import { Route as OfficerLandSearchRouteImport } from './routes/officer.land-search'
import { Route as OfficerMapRouteImport } from './routes/officer.map'
import { Route as OfficerPriorityRouteImport } from './routes/officer.priority'
import { Route as OfficerReportsRouteImport } from './routes/officer.reports'
import { Route as OfficerRtkRouteImport } from './routes/officer.rtk'
import { Route as OfficerSimulatorRouteImport } from './routes/officer.simulator'
import { Route as OfficerLandIdRouteImport } from './routes/officer.land.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenRoute = CitizenRouteImport.update({
  id: '/citizen',
  path: '/citizen',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenLoginRoute = CitizenLoginRouteImport.update({
  id: '/citizen-login',
  path: '/citizen-login',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerRoute = OfficerRouteImport.update({
  id: '/officer',
  path: '/officer',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerLoginRoute = OfficerLoginRouteImport.update({
  id: '/officer-login',
  path: '/officer-login',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenIndexRoute = CitizenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenAreaBoundaryRoute = CitizenAreaBoundaryRouteImport.update({
  id: '/area-boundary',
  path: '/area-boundary',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenDocumentsRoute = CitizenDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenLandHealthRoute = CitizenLandHealthRouteImport.update({
  id: '/land-health',
  path: '/land-health',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenMapRoute = CitizenMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenMyLandsRoute = CitizenMyLandsRouteImport.update({
  id: '/my-lands',
  path: '/my-lands',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenNotificationsRoute = CitizenNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenProfileRoute = CitizenProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenReVerificationRoute = CitizenReVerificationRouteImport.update({
  id: '/re-verification',
  path: '/re-verification',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenReportIssueRoute = CitizenReportIssueRouteImport.update({
  id: '/report-issue',
  path: '/report-issue',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenReportsRoute = CitizenReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenRequestsRoute = CitizenRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenSearchLandRoute = CitizenSearchLandRouteImport.update({
  id: '/search-land',
  path: '/search-land',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenSurveyHistoryRoute = CitizenSurveyHistoryRouteImport.update({
  id: '/survey-history',
  path: '/survey-history',
  getParentRoute: () => CitizenRoute,
} as any)
const OfficerIndexRoute = OfficerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerAiDiscrepancyRoute = OfficerAiDiscrepancyRouteImport.update({
  id: '/ai-discrepancy',
  path: '/ai-discrepancy',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerAuditTrailRoute = OfficerAuditTrailRouteImport.update({
  id: '/audit-trail',
  path: '/audit-trail',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerBoundaryEvolutionRoute =
  OfficerBoundaryEvolutionRouteImport.update({
    id: '/boundary-evolution',
    path: '/boundary-evolution',
    getParentRoute: () => OfficerRoute,
  } as any)
const OfficerConfidenceRoute = OfficerConfidenceRouteImport.update({
  id: '/confidence',
  path: '/confidence',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerCrossParcelRoute = OfficerCrossParcelRouteImport.update({
  id: '/cross-parcel',
  path: '/cross-parcel',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerDroneSurveyRoute = OfficerDroneSurveyRouteImport.update({
  id: '/drone-survey',
  path: '/drone-survey',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerEarlyWarningRoute = OfficerEarlyWarningRouteImport.update({
  id: '/early-warning',
  path: '/early-warning',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerEvidenceConflictRoute = OfficerEvidenceConflictRouteImport.update({
  id: '/evidence-conflict',
  path: '/evidence-conflict',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerFieldVerificationRoute =
  OfficerFieldVerificationRouteImport.update({
    id: '/field-verification',
    path: '/field-verification',
    getParentRoute: () => OfficerRoute,
  } as any)
const OfficerLandRecordsRoute = OfficerLandRecordsRouteImport.update({
  id: '/land-records',
  path: '/land-records',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerLandSearchRoute = OfficerLandSearchRouteImport.update({
  id: '/land-search',
  path: '/land-search',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerMapRoute = OfficerMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerPriorityRoute = OfficerPriorityRouteImport.update({
  id: '/priority',
  path: '/priority',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerReportsRoute = OfficerReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerRtkRoute = OfficerRtkRouteImport.update({
  id: '/rtk',
  path: '/rtk',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerSimulatorRoute = OfficerSimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerLandIdRoute = OfficerLandIdRouteImport.update({
  id: '/land/$id',
  path: '/land/$id',
  getParentRoute: () => OfficerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/citizen': typeof CitizenRouteWithChildren
  '/citizen-login': typeof CitizenLoginRoute
  '/officer': typeof OfficerRouteWithChildren
  '/officer-login': typeof OfficerLoginRoute
  '/citizen/area-boundary': typeof CitizenAreaBoundaryRoute
  '/citizen/documents': typeof CitizenDocumentsRoute
  '/citizen/land-health': typeof CitizenLandHealthRoute
  '/citizen/map': typeof CitizenMapRoute
  '/citizen/my-lands': typeof CitizenMyLandsRoute
  '/citizen/notifications': typeof CitizenNotificationsRoute
  '/citizen/profile': typeof CitizenProfileRoute
  '/citizen/re-verification': typeof CitizenReVerificationRoute
  '/citizen/report-issue': typeof CitizenReportIssueRoute
  '/citizen/reports': typeof CitizenReportsRoute
  '/citizen/requests': typeof CitizenRequestsRoute
  '/citizen/search-land': typeof CitizenSearchLandRoute
  '/citizen/survey-history': typeof CitizenSurveyHistoryRoute
  '/officer/ai-discrepancy': typeof OfficerAiDiscrepancyRoute
  '/officer/audit-trail': typeof OfficerAuditTrailRoute
  '/officer/boundary-evolution': typeof OfficerBoundaryEvolutionRoute
  '/officer/confidence': typeof OfficerConfidenceRoute
  '/officer/cross-parcel': typeof OfficerCrossParcelRoute
  '/officer/drone-survey': typeof OfficerDroneSurveyRoute
  '/officer/early-warning': typeof OfficerEarlyWarningRoute
  '/officer/evidence-conflict': typeof OfficerEvidenceConflictRoute
  '/officer/field-verification': typeof OfficerFieldVerificationRoute
  '/officer/land-records': typeof OfficerLandRecordsRoute
  '/officer/land-search': typeof OfficerLandSearchRoute
  '/officer/map': typeof OfficerMapRoute
  '/officer/priority': typeof OfficerPriorityRoute
  '/officer/reports': typeof OfficerReportsRoute
  '/officer/rtk': typeof OfficerRtkRoute
  '/officer/simulator': typeof OfficerSimulatorRoute
  '/citizen/': typeof CitizenIndexRoute
  '/officer/': typeof OfficerIndexRoute
  '/officer/land/$id': typeof OfficerLandIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/citizen-login': typeof CitizenLoginRoute
  '/officer-login': typeof OfficerLoginRoute
  '/citizen/area-boundary': typeof CitizenAreaBoundaryRoute
  '/citizen/documents': typeof CitizenDocumentsRoute
  '/citizen/land-health': typeof CitizenLandHealthRoute
  '/citizen/map': typeof CitizenMapRoute
  '/citizen/my-lands': typeof CitizenMyLandsRoute
  '/citizen/notifications': typeof CitizenNotificationsRoute
  '/citizen/profile': typeof CitizenProfileRoute
  '/citizen/re-verification': typeof CitizenReVerificationRoute
  '/citizen/report-issue': typeof CitizenReportIssueRoute
  '/citizen/reports': typeof CitizenReportsRoute
  '/citizen/requests': typeof CitizenRequestsRoute
  '/citizen/search-land': typeof CitizenSearchLandRoute
  '/citizen/survey-history': typeof CitizenSurveyHistoryRoute
  '/officer/ai-discrepancy': typeof OfficerAiDiscrepancyRoute
  '/officer/audit-trail': typeof OfficerAuditTrailRoute
  '/officer/boundary-evolution': typeof OfficerBoundaryEvolutionRoute
  '/officer/confidence': typeof OfficerConfidenceRoute
  '/officer/cross-parcel': typeof OfficerCrossParcelRoute
  '/officer/drone-survey': typeof OfficerDroneSurveyRoute
  '/officer/early-warning': typeof OfficerEarlyWarningRoute
  '/officer/evidence-conflict': typeof OfficerEvidenceConflictRoute
  '/officer/field-verification': typeof OfficerFieldVerificationRoute
  '/officer/land-records': typeof OfficerLandRecordsRoute
  '/officer/land-search': typeof OfficerLandSearchRoute
  '/officer/map': typeof OfficerMapRoute
  '/officer/priority': typeof OfficerPriorityRoute
  '/officer/reports': typeof OfficerReportsRoute
  '/officer/rtk': typeof OfficerRtkRoute
  '/officer/simulator': typeof OfficerSimulatorRoute
  '/citizen': typeof CitizenIndexRoute
  '/officer': typeof OfficerIndexRoute
  '/officer/land/$id': typeof OfficerLandIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/citizen': typeof CitizenRouteWithChildren
  '/citizen-login': typeof CitizenLoginRoute
  '/officer': typeof OfficerRouteWithChildren
  '/officer-login': typeof OfficerLoginRoute
  '/citizen/area-boundary': typeof CitizenAreaBoundaryRoute
  '/citizen/documents': typeof CitizenDocumentsRoute
  '/citizen/land-health': typeof CitizenLandHealthRoute
  '/citizen/map': typeof CitizenMapRoute
  '/citizen/my-lands': typeof CitizenMyLandsRoute
  '/citizen/notifications': typeof CitizenNotificationsRoute
  '/citizen/profile': typeof CitizenProfileRoute
  '/citizen/re-verification': typeof CitizenReVerificationRoute
  '/citizen/report-issue': typeof CitizenReportIssueRoute
  '/citizen/reports': typeof CitizenReportsRoute
  '/citizen/requests': typeof CitizenRequestsRoute
  '/citizen/search-land': typeof CitizenSearchLandRoute
  '/citizen/survey-history': typeof CitizenSurveyHistoryRoute
  '/officer/ai-discrepancy': typeof OfficerAiDiscrepancyRoute
  '/officer/audit-trail': typeof OfficerAuditTrailRoute
  '/officer/boundary-evolution': typeof OfficerBoundaryEvolutionRoute
  '/officer/confidence': typeof OfficerConfidenceRoute
  '/officer/cross-parcel': typeof OfficerCrossParcelRoute
  '/officer/drone-survey': typeof OfficerDroneSurveyRoute
  '/officer/early-warning': typeof OfficerEarlyWarningRoute
  '/officer/evidence-conflict': typeof OfficerEvidenceConflictRoute
  '/officer/field-verification': typeof OfficerFieldVerificationRoute
  '/officer/land-records': typeof OfficerLandRecordsRoute
  '/officer/land-search': typeof OfficerLandSearchRoute
  '/officer/map': typeof OfficerMapRoute
  '/officer/priority': typeof OfficerPriorityRoute
  '/officer/reports': typeof OfficerReportsRoute
  '/officer/rtk': typeof OfficerRtkRoute
  '/officer/simulator': typeof OfficerSimulatorRoute
  '/citizen/': typeof CitizenIndexRoute
  '/officer/': typeof OfficerIndexRoute
  '/officer/land/$id': typeof OfficerLandIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/citizen'
    | '/citizen-login'
    | '/officer'
    | '/officer-login'
    | '/citizen/area-boundary'
    | '/citizen/documents'
    | '/citizen/land-health'
    | '/citizen/map'
    | '/citizen/my-lands'
    | '/citizen/notifications'
    | '/citizen/profile'
    | '/citizen/re-verification'
    | '/citizen/report-issue'
    | '/citizen/reports'
    | '/citizen/requests'
    | '/citizen/search-land'
    | '/citizen/survey-history'
    | '/officer/ai-discrepancy'
    | '/officer/audit-trail'
    | '/officer/boundary-evolution'
    | '/officer/confidence'
    | '/officer/cross-parcel'
    | '/officer/drone-survey'
    | '/officer/early-warning'
    | '/officer/evidence-conflict'
    | '/officer/field-verification'
    | '/officer/land-records'
    | '/officer/land-search'
    | '/officer/map'
    | '/officer/priority'
    | '/officer/reports'
    | '/officer/rtk'
    | '/officer/simulator'
    | '/citizen/'
    | '/officer/'
    | '/officer/land/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/citizen-login'
    | '/officer-login'
    | '/citizen/area-boundary'
    | '/citizen/documents'
    | '/citizen/land-health'
    | '/citizen/map'
    | '/citizen/my-lands'
    | '/citizen/notifications'
    | '/citizen/profile'
    | '/citizen/re-verification'
    | '/citizen/report-issue'
    | '/citizen/reports'
    | '/citizen/requests'
    | '/citizen/search-land'
    | '/citizen/survey-history'
    | '/officer/ai-discrepancy'
    | '/officer/audit-trail'
    | '/officer/boundary-evolution'
    | '/officer/confidence'
    | '/officer/cross-parcel'
    | '/officer/drone-survey'
    | '/officer/early-warning'
    | '/officer/evidence-conflict'
    | '/officer/field-verification'
    | '/officer/land-records'
    | '/officer/land-search'
    | '/officer/map'
    | '/officer/priority'
    | '/officer/reports'
    | '/officer/rtk'
    | '/officer/simulator'
    | '/citizen'
    | '/officer'
    | '/officer/land/$id'
  id:
    | '__root__'
    | '/'
    | '/citizen'
    | '/citizen-login'
    | '/officer'
    | '/officer-login'
    | '/citizen/area-boundary'
    | '/citizen/documents'
    | '/citizen/land-health'
    | '/citizen/map'
    | '/citizen/my-lands'
    | '/citizen/notifications'
    | '/citizen/profile'
    | '/citizen/re-verification'
    | '/citizen/report-issue'
    | '/citizen/reports'
    | '/citizen/requests'
    | '/citizen/search-land'
    | '/citizen/survey-history'
    | '/officer/ai-discrepancy'
    | '/officer/audit-trail'
    | '/officer/boundary-evolution'
    | '/officer/confidence'
    | '/officer/cross-parcel'
    | '/officer/drone-survey'
    | '/officer/early-warning'
    | '/officer/evidence-conflict'
    | '/officer/field-verification'
    | '/officer/land-records'
    | '/officer/land-search'
    | '/officer/map'
    | '/officer/priority'
    | '/officer/reports'
    | '/officer/rtk'
    | '/officer/simulator'
    | '/citizen/'
    | '/officer/'
    | '/officer/land/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CitizenRoute: typeof CitizenRouteWithChildren
  CitizenLoginRoute: typeof CitizenLoginRoute
  OfficerRoute: typeof OfficerRouteWithChildren
  OfficerLoginRoute: typeof OfficerLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen': {
      id: '/citizen'
      path: '/citizen'
      fullPath: '/citizen'
      preLoaderRoute: typeof CitizenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen-login': {
      id: '/citizen-login'
      path: '/citizen-login'
      fullPath: '/citizen-login'
      preLoaderRoute: typeof CitizenLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer': {
      id: '/officer'
      path: '/officer'
      fullPath: '/officer'
      preLoaderRoute: typeof OfficerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer-login': {
      id: '/officer-login'
      path: '/officer-login'
      fullPath: '/officer-login'
      preLoaderRoute: typeof OfficerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/': {
      id: '/citizen/'
      path: '/'
      fullPath: '/citizen/'
      preLoaderRoute: typeof CitizenIndexRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/area-boundary': {
      id: '/citizen/area-boundary'
      path: '/area-boundary'
      fullPath: '/citizen/area-boundary'
      preLoaderRoute: typeof CitizenAreaBoundaryRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/documents': {
      id: '/citizen/documents'
      path: '/documents'
      fullPath: '/citizen/documents'
      preLoaderRoute: typeof CitizenDocumentsRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/land-health': {
      id: '/citizen/land-health'
      path: '/land-health'
      fullPath: '/citizen/land-health'
      preLoaderRoute: typeof CitizenLandHealthRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/map': {
      id: '/citizen/map'
      path: '/map'
      fullPath: '/citizen/map'
      preLoaderRoute: typeof CitizenMapRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/my-lands': {
      id: '/citizen/my-lands'
      path: '/my-lands'
      fullPath: '/citizen/my-lands'
      preLoaderRoute: typeof CitizenMyLandsRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/notifications': {
      id: '/citizen/notifications'
      path: '/notifications'
      fullPath: '/citizen/notifications'
      preLoaderRoute: typeof CitizenNotificationsRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/profile': {
      id: '/citizen/profile'
      path: '/profile'
      fullPath: '/citizen/profile'
      preLoaderRoute: typeof CitizenProfileRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/re-verification': {
      id: '/citizen/re-verification'
      path: '/re-verification'
      fullPath: '/citizen/re-verification'
      preLoaderRoute: typeof CitizenReVerificationRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/report-issue': {
      id: '/citizen/report-issue'
      path: '/report-issue'
      fullPath: '/citizen/report-issue'
      preLoaderRoute: typeof CitizenReportIssueRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/reports': {
      id: '/citizen/reports'
      path: '/reports'
      fullPath: '/citizen/reports'
      preLoaderRoute: typeof CitizenReportsRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/requests': {
      id: '/citizen/requests'
      path: '/requests'
      fullPath: '/citizen/requests'
      preLoaderRoute: typeof CitizenRequestsRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/search-land': {
      id: '/citizen/search-land'
      path: '/search-land'
      fullPath: '/citizen/search-land'
      preLoaderRoute: typeof CitizenSearchLandRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/survey-history': {
      id: '/citizen/survey-history'
      path: '/survey-history'
      fullPath: '/citizen/survey-history'
      preLoaderRoute: typeof CitizenSurveyHistoryRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/officer/': {
      id: '/officer/'
      path: '/'
      fullPath: '/officer/'
      preLoaderRoute: typeof OfficerIndexRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/ai-discrepancy': {
      id: '/officer/ai-discrepancy'
      path: '/ai-discrepancy'
      fullPath: '/officer/ai-discrepancy'
      preLoaderRoute: typeof OfficerAiDiscrepancyRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/audit-trail': {
      id: '/officer/audit-trail'
      path: '/audit-trail'
      fullPath: '/officer/audit-trail'
      preLoaderRoute: typeof OfficerAuditTrailRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/boundary-evolution': {
      id: '/officer/boundary-evolution'
      path: '/boundary-evolution'
      fullPath: '/officer/boundary-evolution'
      preLoaderRoute: typeof OfficerBoundaryEvolutionRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/confidence': {
      id: '/officer/confidence'
      path: '/confidence'
      fullPath: '/officer/confidence'
      preLoaderRoute: typeof OfficerConfidenceRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/cross-parcel': {
      id: '/officer/cross-parcel'
      path: '/cross-parcel'
      fullPath: '/officer/cross-parcel'
      preLoaderRoute: typeof OfficerCrossParcelRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/drone-survey': {
      id: '/officer/drone-survey'
      path: '/drone-survey'
      fullPath: '/officer/drone-survey'
      preLoaderRoute: typeof OfficerDroneSurveyRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/early-warning': {
      id: '/officer/early-warning'
      path: '/early-warning'
      fullPath: '/officer/early-warning'
      preLoaderRoute: typeof OfficerEarlyWarningRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/evidence-conflict': {
      id: '/officer/evidence-conflict'
      path: '/evidence-conflict'
      fullPath: '/officer/evidence-conflict'
      preLoaderRoute: typeof OfficerEvidenceConflictRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/field-verification': {
      id: '/officer/field-verification'
      path: '/field-verification'
      fullPath: '/officer/field-verification'
      preLoaderRoute: typeof OfficerFieldVerificationRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/land-records': {
      id: '/officer/land-records'
      path: '/land-records'
      fullPath: '/officer/land-records'
      preLoaderRoute: typeof OfficerLandRecordsRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/land-search': {
      id: '/officer/land-search'
      path: '/land-search'
      fullPath: '/officer/land-search'
      preLoaderRoute: typeof OfficerLandSearchRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/map': {
      id: '/officer/map'
      path: '/map'
      fullPath: '/officer/map'
      preLoaderRoute: typeof OfficerMapRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/priority': {
      id: '/officer/priority'
      path: '/priority'
      fullPath: '/officer/priority'
      preLoaderRoute: typeof OfficerPriorityRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/reports': {
      id: '/officer/reports'
      path: '/reports'
      fullPath: '/officer/reports'
      preLoaderRoute: typeof OfficerReportsRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/rtk': {
      id: '/officer/rtk'
      path: '/rtk'
      fullPath: '/officer/rtk'
      preLoaderRoute: typeof OfficerRtkRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/simulator': {
      id: '/officer/simulator'
      path: '/simulator'
      fullPath: '/officer/simulator'
      preLoaderRoute: typeof OfficerSimulatorRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/land/$id': {
      id: '/officer/land/$id'
      path: '/land/$id'
      fullPath: '/officer/land/$id'
      preLoaderRoute: typeof OfficerLandIdRouteImport
      parentRoute: typeof OfficerRoute
    }
  }
}

interface CitizenRouteChildren {
  CitizenAreaBoundaryRoute: typeof CitizenAreaBoundaryRoute
  CitizenDocumentsRoute: typeof CitizenDocumentsRoute
  CitizenLandHealthRoute: typeof CitizenLandHealthRoute
  CitizenMapRoute: typeof CitizenMapRoute
  CitizenMyLandsRoute: typeof CitizenMyLandsRoute
  CitizenNotificationsRoute: typeof CitizenNotificationsRoute
  CitizenProfileRoute: typeof CitizenProfileRoute
  CitizenReVerificationRoute: typeof CitizenReVerificationRoute
  CitizenReportIssueRoute: typeof CitizenReportIssueRoute
  CitizenReportsRoute: typeof CitizenReportsRoute
  CitizenRequestsRoute: typeof CitizenRequestsRoute
  CitizenSearchLandRoute: typeof CitizenSearchLandRoute
  CitizenSurveyHistoryRoute: typeof CitizenSurveyHistoryRoute
  CitizenIndexRoute: typeof CitizenIndexRoute
}

const CitizenRouteChildren: CitizenRouteChildren = {
  CitizenAreaBoundaryRoute: CitizenAreaBoundaryRoute,
  CitizenDocumentsRoute: CitizenDocumentsRoute,
  CitizenLandHealthRoute: CitizenLandHealthRoute,
  CitizenMapRoute: CitizenMapRoute,
  CitizenMyLandsRoute: CitizenMyLandsRoute,
  CitizenNotificationsRoute: CitizenNotificationsRoute,
  CitizenProfileRoute: CitizenProfileRoute,
  CitizenReVerificationRoute: CitizenReVerificationRoute,
  CitizenReportIssueRoute: CitizenReportIssueRoute,
  CitizenReportsRoute: CitizenReportsRoute,
  CitizenRequestsRoute: CitizenRequestsRoute,
  CitizenSearchLandRoute: CitizenSearchLandRoute,
  CitizenSurveyHistoryRoute: CitizenSurveyHistoryRoute,
  CitizenIndexRoute: CitizenIndexRoute,
}

const CitizenRouteWithChildren =
  CitizenRoute._addFileChildren(CitizenRouteChildren)

interface OfficerRouteChildren {
  OfficerAiDiscrepancyRoute: typeof OfficerAiDiscrepancyRoute
  OfficerAuditTrailRoute: typeof OfficerAuditTrailRoute
  OfficerBoundaryEvolutionRoute: typeof OfficerBoundaryEvolutionRoute
  OfficerConfidenceRoute: typeof OfficerConfidenceRoute
  OfficerCrossParcelRoute: typeof OfficerCrossParcelRoute
  OfficerDroneSurveyRoute: typeof OfficerDroneSurveyRoute
  OfficerEarlyWarningRoute: typeof OfficerEarlyWarningRoute
  OfficerEvidenceConflictRoute: typeof OfficerEvidenceConflictRoute
  OfficerFieldVerificationRoute: typeof OfficerFieldVerificationRoute
  OfficerLandRecordsRoute: typeof OfficerLandRecordsRoute
  OfficerLandSearchRoute: typeof OfficerLandSearchRoute
  OfficerMapRoute: typeof OfficerMapRoute
  OfficerPriorityRoute: typeof OfficerPriorityRoute
  OfficerReportsRoute: typeof OfficerReportsRoute
  OfficerRtkRoute: typeof OfficerRtkRoute
  OfficerSimulatorRoute: typeof OfficerSimulatorRoute
  OfficerIndexRoute: typeof OfficerIndexRoute
  OfficerLandIdRoute: typeof OfficerLandIdRoute
}

const OfficerRouteChildren: OfficerRouteChildren = {
  OfficerAiDiscrepancyRoute: OfficerAiDiscrepancyRoute,
  OfficerAuditTrailRoute: OfficerAuditTrailRoute,
  OfficerBoundaryEvolutionRoute: OfficerBoundaryEvolutionRoute,
  OfficerConfidenceRoute: OfficerConfidenceRoute,
  OfficerCrossParcelRoute: OfficerCrossParcelRoute,
  OfficerDroneSurveyRoute: OfficerDroneSurveyRoute,
  OfficerEarlyWarningRoute: OfficerEarlyWarningRoute,
  OfficerEvidenceConflictRoute: OfficerEvidenceConflictRoute,
  OfficerFieldVerificationRoute: OfficerFieldVerificationRoute,
  OfficerLandRecordsRoute: OfficerLandRecordsRoute,
  OfficerLandSearchRoute: OfficerLandSearchRoute,
  OfficerMapRoute: OfficerMapRoute,
  OfficerPriorityRoute: OfficerPriorityRoute,
  OfficerReportsRoute: OfficerReportsRoute,
  OfficerRtkRoute: OfficerRtkRoute,
  OfficerSimulatorRoute: OfficerSimulatorRoute,
  OfficerIndexRoute: OfficerIndexRoute,
  OfficerLandIdRoute: OfficerLandIdRoute,
}

const OfficerRouteWithChildren =
  OfficerRoute._addFileChildren(OfficerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CitizenRoute: CitizenRouteWithChildren,
  CitizenLoginRoute: CitizenLoginRoute,
  OfficerRoute: OfficerRouteWithChildren,
  OfficerLoginRoute: OfficerLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
